### ISSUE TITLE
Feature Request exporting vectors/data frame to text file

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#29]
Do you have plans to add this feature where we could export data frame/vectors/matrices to text file?

**Comment by ronkok** [comment]
You can already copy a Hurmet result onto the clipboard, but it is a bit awkward. The awkward part is that you must first select a Hurmet calculation cell without opening the source code. To do that, place the selection point just after the cell, hold down the shift key, and hit the left arrow button.

After you have selected (but not opened) a cell, you can hit Ctrl+C for copy. Hurmet will save the result of the cell onto the clipboard.

I need to clean up how that clipboard text writes a vector or matrix. I'll do that later today.

I am also considering an optional format for saved documents. The optional format would save calculation results, not just the user entries for each calculation cell.

**Comment by swopnil123** [comment]
Yes, we can copy to clipboard that way. Pasting to text file is easy. The format remains intact. However Excel messes it up. Lot of post processing is required.

This is text file
![image](https://github.com/ronkok/Hurmet/assets/17706904/84050c5f-871d-4e19-91ed-cf430fc7fb95)

This is excel
![image](https://github.com/ronkok/Hurmet/assets/17706904/c008d187-87b2-44ff-a1a0-6b56c4e05878)

**Comment by ronkok** [comment]
In your data frame example, the only post-processing necessary is the deletion of the opening and closing backtick delimiters. Then it will paste in nicely.

For the general case, I will point out that a browser-based program cannot do a universally compatible copy. Desktop programs are different. They typically copy in several formats (proprietary, HTML, RTF, plain text, etc.) and put all the formats onto the clipboard. Then when an app does a paste, it can choose its compatible format.

Running in the browser, Hurmet cannot create multiple formats. The browser's native copy format is HTML. Using JavaScript, I can pre-empt that format and substitute a plain text version instead. Since I only get one format, I choose to write plain text that can be pasted directly into a Hurmet document.

Pasting into other apps will sometimes require some post-processing. I know of no way around that.

I have added a new option to the Hurmet Markdown menu. You can now copy a version that includes calculation results.

**Comment by swopnil123** [comment]
Thanks! That solves a lot of problem.
